# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

# Logging configuration
logging:
  path: /logs/demo
  file: MyDemo.log
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

#spring.boot.admin.url: http://localhost:8080
