# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  redis:
    database: 0
    host: ${WP_REDIS_HOST:114.212.87.73}
    #host: 114.212.87.73
    password:
    port: ${WP_REDIS_PORT:6379}
    #port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 0

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

# Logging configuration
logging:
  path: /logs/demo
  file: MyDemo.log
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg%n'
    #%logger{15} -

#spring.boot.admin.url: http://localhost:8080